import { useState } from "react";

// Displays outreach draft with copy-to-clipboard action and result messaging.
const OutreachEmailCard = ({ emailResult }) => {
  const [copied, setCopied] = useState(false);

  // Copies generated email text for quick SDR workflow handoff.
  const copyText = async () => {
    if (!emailResult?.email) return;
    await navigator.clipboard.writeText(emailResult.email);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <h3 className="mb-4 text-lg font-semibold text-slate-800">Outreach Email</h3>
      {emailResult?.status === "missing_key" ? (
        <p className="text-sm text-slate-700">
          Add your Anthropic API key at the top of the page to generate a personalized outreach email for this lead.
        </p>
      ) : emailResult?.status !== "ok" ? (
        <div>
          <p className="text-sm text-slate-700">Email generation failed.</p>
          <p className="mt-1 text-sm text-slate-700">
            {emailResult?.error
              ? emailResult.error
              : "Check your Anthropic API key, billing, and model access, then try again."}
          </p>
        </div>
      ) : (
        <div>
          <textarea
            readOnly
            value={emailResult?.email || ""}
            className="min-h-52 w-full rounded-lg border border-slate-300 p-3 text-sm text-slate-700"
          />
          <button
            type="button"
            onClick={copyText}
            className="mt-3 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700"
          >
            {copied ? "✓ Copied" : "Copy to Clipboard"}
          </button>
          <p className="mt-2 text-xs text-slate-500">
            Generated by Claude AI using enriched Census, DataUSA, and Wikipedia data
          </p>
        </div>
      )}
    </div>
  );
};

export default OutreachEmailCard;
